#!/bin/bash

. /etc/include-media.cfg

option=$1
file=$2
path=""

if [ "$option" = "-f" ]; then
  path=$FILMS_PATH
else
  path=$TV_SHOWS_PATH
fi

echo "moving " $file " to " $path
mv $file $path
e-binary '{ "jsonrpc": "2.0", "method": "VideoLibrary.Scan", "id": "mybash"}' -H 'content-type: application/json;' http://localhost:$HTTP_REMOTE_PORT/jsonrpc "reloading video library"



